### ISSUE TITLE
Why is StyleCop a dependency for the BearerToken nuget package?

### ISSUE THREAD

**Issue by wyrmbounds** [unosquare/embedio-extras#11]
Can this dependency be removed? I'd prefer not to have this in my project.

**Comment by geoperez** [comment]
You are right, it's development dependency and should not be in the nuget. Let you know when it's done.

**Comment by geoperez** [comment]
Please check new nuget https://www.nuget.org/packages/EmbedIO.BearerToken/1.2.1

**Comment by wyrmbounds** [comment]
Perfect, thank you!
