### ISSUE TITLE
cannot convert from 'Unosquare.Labs.EmbedIO.BearerToken.BearerTokenModule' to 'Unosquare.Labs.EmbedIO.IWebModule'

### ISSUE THREAD

**Issue by afsharm** [unosquare/embedio-extras#2]
Hi, 
My .Net 4.5 app is using EmbedIO 1.0.19 and EmbedIO.BearerToken 1.0.0 packages from nuget. With this code:

```
            var basicAuthProvider = new BasicAuthorizationServerProvider();
            var routes = new[] { "" };
            server.RegisterModule(new BearerTokenModule(basicAuthProvider, routes));
```

I get error: cannot convert from 'Unosquare.Labs.EmbedIO.BearerToken.BearerTokenModule' to 'Unosquare.Labs.EmbedIO.IWebModule'

How can I correct it?

**Comment by geoperez** [comment]
Hi @afsharm , you are right, the BearerTokenModule was expecting an older EmbedIO version. I just published a new EmbedIO.BearerToken Nuget, please update your project and let me know if it works.

**Comment by afsharm** [comment]
Hi @geoperez, Thank you very much for your quick response. New nugets solved the problem. Now my selected requests are secured correctly. 

Can I ask you what is recommended way for generating a Bearer Token regarding embedio?

**Comment by geoperez** [comment]
The Bearer token is generated using the standard JSON Web Tokens (https://jwt.io/introduction/).
