### ISSUE TITLE
Bearer Token routes not working with WebApiController routes

### ISSUE THREAD

**Issue by gitbitlit** [unosquare/embedio-extras#20]
It looks like routes passed to BearerTokenModule are not working with WebApiController routes.

It works if API Controller routes and Bearer token routes are as follows :
- route begin with "/" and there should NOT be anymore "/"
- route is just wildcard "*"
- route is null (default)

**Comment by geoperez** [comment]
I changed the logic of the module. I will check only the routes in the base URL.

For example:

```csharp
 using var server = new WebServer(url)
                .WithBearerToken("/api", "0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9eyJjbGF")
                .WithModule(new ApiModule("/api")); // this module will be secured
```

**Comment by marculescu** [comment]
I cannot setup the Bearer Token Module properly. I don't know where to ask this. I asked another EmbedIO related [question](https://stackoverflow.com/questions/58718698/how-to-setup-an-exception-handler-in-embedio-web-api) on SO, but without luck, so I'm writing there. 

I'm using the server with the following code:

```
WebServerEmbedded = new EmbedIO.WebServer(
    opt => opt
        .WithUrlPrefix("http://192.168.1.11:8787")
        .WithMode(HttpListenerMode.EmbedIO));
        
var webApiModule = new WebApiModule("/api").WithController<SomeController>();

WebServerEmbedded
    .WithCors()
    .WithModule(webApiModule)
    .WithStaticFolder("/", staticFolder, true);
```

Now I'd like to use the Bearer Token Module, to secure only the API module, but I'm failing to see how to configure the server to invoke the module for the path '/token' and also for the path '/api'.

With this code:

```
WebServerEmbedded        
    .WithCors()
    .WithBearerToken("/api", "0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9eyJjbGF")
    .WithModule(webApiModule)
    .WithStaticFolder("/", staticFolder, true);
```

I get the following when running a POST http://192.168.1.11:8787/token 

```
13:46:01.663 DBG >> [WebServer] [j7jRpD384Um9U3prjxXp6Q] 192.168.1.11:54269: POST /token - PostmanRuntime/7.21.0
13:46:01.666 DBG >> [WebServer] [j7jRpD384Um9U3prjxXp6Q] Processing with <CorsModule>.
13:46:01.672 DBG >> [WebServer] [j7jRpD384Um9U3prjxXp6Q] Processing with <FileModule>.
13:46:01.684 ERR >> [WebServer] [j7jRpD384Um9U3prjxXp6Q] HTTP exception 404
```

If I cram another WithBearerToken:

```
WebServerEmbedded        
    .WithCors()
    .WithBearerToken("/token", "0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9eyJjbGF")
    .WithBearerToken("/api", "0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9eyJjbGF")
    .WithModule(webApiModule)
    .WithStaticFolder("/", staticFolder, true);
```

I get this:

```
14:01:15.791 DBG >> [WebServer] [XsmmvW0ypEymollyxzDLdA] 192.168.1.11:54385: POST /token - PostmanRuntime/7.21.0
14:01:15.794 DBG >> [WebServer] [XsmmvW0ypEymollyxzDLdA] Processing with <CorsModule>.
14:01:15.801 DBG >> [WebServer] [XsmmvW0ypEymollyxzDLdA] Processing with <BearerTokenModule>.
14:01:15.811 ERR >> [WebServer] [XsmmvW0ypEymollyxzDLdA] HTTP exception 401
```

I think the documentation could be improved here. It seems a bit obsolete anyway, since it's not possible to configure the module with multiple routes:
server.WithBearerToken("/", basicAuthProvider, routes)

Thanks.

**Comment by geoperez** [comment]
You need to point the token endpoint to your base route. So, if you are securing `/api` then your token endpoint is `/api/token`.

And you are right, the documentation is outdated, I'll update it.

**Comment by marculescu** [comment]
Thanks, Geovanni. If you have time, could you please have a look at the [SO question](https://stackoverflow.com/questions/58718698/how-to-setup-an-exception-handler-in-embedio-web-api) I mentioned?

**Comment by geoperez** [comment]
Sure, I will.

**Comment by geoperez** [comment]
@marculescu. I don't get your question. I saw you want to use custom Exception, let's say InvalidOperationException, and throw it and transform this to an HTTPException. Is this correct?

**Comment by marculescu** [comment]
Yes, this is correct. I replied with an example on the SO question.

**Comment by marculescu** [comment]
Sorry for using this issue to ask questions (maybe you can indicate a different location for further inquiries), but getting back to the Bearer Token Module, is it possible to identify an internal user of my application with the token?

I can see a [GetPrincipal](https://github.com/unosquare/embedio-extras/blob/master/src/Unosquare.Labs.EmbedIO.BearerToken/Extensions.cs#L74) method but it's not clear if this is what I should use and how.

Thanks.

**Comment by marculescu** [comment]
I posted a new question on SO: https://stackoverflow.com/questions/59730311/how-to-setup-the-principal-in-embedio-with-bearer-token-and-api-modules

**Comment by geoperez** [comment]
@marculescu I need to work on this, can you post a new issue in this repo?

**Comment by marculescu** [comment]
Ok, please see #71
